# Example from Ansible Playbooks
- template:
    src: /mytemplates/foo.j2
    dest: /etc/file.conf
    owner: bin
    group: wheel
    mode: 0644

# The same example, but using symbolic modes equivalent to 0644
- template:
    src: /mytemplates/foo.j2
    dest: /etc/file.conf
    owner: bin
    group: wheel
    mode: "u=rw,g=r,o=r"

# Copy a new "sudoers" file into place, after passing validation with visudo
- template:
    src: /mine/sudoers
    dest: /etc/sudoers
    validate: 'visudo -cf %s'

# Update sshd configuration safely, avoid locking yourself out
- template:
    src: etc/ssh/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
    validate: /usr/sbin/sshd -t -f %s
    backup: yes
    
version: "1"
services:
    web:
        image: {{ web_image }}
        ports: {{ web_ports }}
        command: ['sleep', '10']
        dev_overrides:
            environment:
            - DEBUG={{ debug }}
    db: {{ db_service }}
registries: {}

Pass a YAML or JSON file with the --var-file option
Create environment variables
export AC_WEB_IMAGE=centos:7 // will be used as web_image
Add a top-level defaults section to container.yml

---
debug: 1
web_ports:
  - 8000:8000
web_image: "python:2.7"
db_service:
  image: "python:2.7"
  command: sleep 10
  expose:
    - 5432
  environment:
    - POSTGRES_DB_NAME=foobar
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=admin