echo "*****************************************"
ssh edureka@dev.edureka-demo.com "id && echo From edureka@dev.edureka-demo.com"
ssh edureka@prod.edureka-demo.com "id && echo From edureka@prod.edureka-demo.com"
echo "*****************************************"
ssh jenkins_demo@dev.edureka-demo.com "id && echo From jenkins_demo@dev.edureka-demo.com"
ssh jenkins_demo@prod.edureka-demo.com "id && echo From jenkins_demo@prod.edureka-demo.com"
echo "*****************************************"
ssh root@dev.edureka-demo.com "id && echo From root@dev.edureka-demo.com"
ssh root@prod.edureka-demo.com "id && echo From root@prod.edureka-demo.com"
echo "*****************************************"
